server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: CLOUD-PROVIDER-PAYMENT-1 # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          #使用负载均衡动态路由
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/getPaymentById/** # 断言，路径相匹配的进行路由

        - id: CLOUD-PROVIDER-PAYMENT-2
          #uri: http://localhost:8001
          #使用负载均衡动态路由
          uri: lb://CLOUD-PROVIDER-PAYMENT
          predicates:
            - Path=/payment/lb #断言,路径相匹配的进行路由
          #- After 相当于是请求需要在 2020-06-12号15:44:15秒才有效
            - After=2020-06-12T15:44:15.064+08:00[Asia/Shanghai]
          #- Cookie 带上cookie访问 key是username value是wonders
           #- Cookie=username,wonders   #带Cookie，并且username的值为eiletxie
          #- Header=X-Request-Id,\d  #请求头要有 X-Request-Id属性并且值为整数的正则表达式\d
           #- Header=X-Request-Id,\d



eureka:
  instance:
    instance-id: gateway9527
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #集群版
      #defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
      #单机版
      defaultZone: http://localhost:7001/eureka/
